on:
  push:
    branches:
      - workflow-debug
    tags:
    - '*'

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/}\n"
      - uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: luckyframeworkdocker/lucky-crystal
          tags: cache, ${{ steps.get_version.outputs.version }}
          cache_froms: luckyframeworkdocker/lucky-crystal:cache
